function [traj]= CalcTrajectory(r_start,r_goal,no_traj_points)
traj=[linspace(r_start(1),r_goal(1),no_traj_points);...
        linspace(r_start(2),r_goal(2),no_traj_points);...
        linspace(r_start(3),r_goal(3),no_traj_points)];
end