function H = DrawCylinder(P1, P2, R, nVertex, FaceColor, FaceLite)
[RX, RY, RZ] = CylinderCoor(P1, P2, R, nVertex);
H = surface(RX, RY, RZ, ...
  'FaceColor',        FaceColor, ...
  'FaceLighting',     FaceLite, ...
  'EdgeColor',        'none', ...
  'AmbientStrength',  0.5, ...
  'DiffuseStrength',  0.4, ...
  'BackFaceLighting', 'lit', ...
  'Clipping',         'off');
end
%[RX, RY, RZ] = CylinderCoor(P1, P2, R, nVertex)
